package egovframework.stock.com;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class dartData{
	
	public Map<String, Object> setDartApiLv1(String name) {
		List<Map<String, Object>> apiList = new ArrayList<Map<String, Object>>();
		Map<String, Object> resultMap = new HashMap<String , Object>();
		Map<String, Object> apiCd = new HashMap<String , Object>();
		//api_code : apiGrpCd
		apiCd.put("apiLv", "1");
		apiCd.put("apiNum", "0");
		apiCd.put("apiGrpCd", "DS001");
		apiCd.put("apiName", "공시정보");		
		apiList.add(apiCd);
		apiCd = new HashMap<String , Object>();
		apiCd.put("apiLv", "2");
		apiCd.put("apiNum", "0");
		apiCd.put("apiGrpCd", "DS002");
		apiCd.put("apiName", "정기보고서 주요정보");		
		apiList.add(apiCd);
		apiCd = new HashMap<String , Object>();
		apiCd.put("apiLv", "3");
		apiCd.put("apiNum", "0");
		apiCd.put("apiGrpCd", "DS003");
		apiCd.put("apiName", "정기보고서 재무정보");		
		apiList.add(apiCd);
		apiCd = new HashMap<String , Object>();
		apiCd.put("apiLv", "4");
		apiCd.put("apiNum", "0");
		apiCd.put("apiGrpCd", "DS004");
		apiCd.put("apiName", "지분공시 종합정보");		
		apiList.add(apiCd);
		apiCd = new HashMap<String , Object>();
		apiCd.put("apiLv", "5");
		apiCd.put("apiNum", "0");
		apiCd.put("apiGrpCd", "DS005");
		apiCd.put("apiName", "주요사항보고서 주요정보");		
		apiList.add(apiCd);
		apiCd = new HashMap<String , Object>();
		apiCd.put("apiLv", "1");
		apiCd.put("apiNum", "6");
		apiCd.put("apiGrpCd", "DS006");
		apiCd.put("apiName", "증권신고서 주요정보");		
		apiList.add(apiCd);
			
		return resultMap;
	}
	
	public Map<String, Object> setDartApiLv2(String name) {
		List<Map<String, Object>> apiLv2List = new ArrayList<Map<String, Object>>();
		Map<String, Object> resultMap = new HashMap<String , Object>();
		
		Map<String, Object> apiLv2Info = new HashMap<String , Object>();
		//1.공시정보
		//1.1 공시검색
		apiLv2Info.put("apiLv", "1");
		apiLv2Info.put("apiNum", "1");
		apiLv2Info.put("apiGrpCd", "DS001");
		apiLv2Info.put("apiId", "2019001");
		apiLv2Info.put("apiName", "공시검색");
		apiLv2Info.put("apiExplanation", "공시 유형별, 회사별, 날짜별 등 여러가지 조건으로 공시보고서 검색기능을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/list.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "list");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "1");
		apiLv2Info.put("apiNum", "1");
		apiLv2Info.put("apiGrpCd", "DS001");
		apiLv2Info.put("apiId", "2019001");
		apiLv2Info.put("apiName", "공시검색");
		apiLv2Info.put("apiExplanation", "공시 유형별, 회사별, 날짜별 등 여러가지 조건으로 공시보고서 검색기능을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/list.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "list");
		apiLv2List.add(apiLv2Info);

		//1.2 기업개황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "1");
		apiLv2Info.put("apiNum", "2");
		apiLv2Info.put("apiGrpCd", "DS001");
		apiLv2Info.put("apiId", "2019002");
		apiLv2Info.put("apiName", "기업개황");
		apiLv2Info.put("apiExplanation", "DART에 등록되어있는 기업의 개황정보를 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/company.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "company");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "1");
		apiLv2Info.put("apiNum", "2");
		apiLv2Info.put("apiGrpCd", "DS001");
		apiLv2Info.put("apiId", "2019002");
		apiLv2Info.put("apiName", "기업개황");
		apiLv2Info.put("apiExplanation", "DART에 등록되어있는 기업의 개황정보를 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/company.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "company");
		apiLv2List.add(apiLv2Info);
		
		//1.3 공시서류원본파일
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "1");
		apiLv2Info.put("apiNum", "3");
		apiLv2Info.put("apiGrpCd", "DS001");
		apiLv2Info.put("apiId", "2019003");
		apiLv2Info.put("apiName", "공시서류원본파일");
		apiLv2Info.put("apiExplanation", "공시보고서 원본파일을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/document.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "ZIP");
		apiLv2Info.put("gubun", "document");
		apiLv2List.add(apiLv2Info);
		
		//1.4 고유번호
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "1");
		apiLv2Info.put("apiNum", "4");
		apiLv2Info.put("apiGrpCd", "DS001");
		apiLv2Info.put("apiId", "2019018");
		apiLv2Info.put("apiName", "고유번호");
		apiLv2Info.put("apiExplanation", "DART에 등록되어있는 공시대상회사의 고유번호,회사명,종목코드, 최근변경일자를 파일로 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/corpCode.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "ZIP");
		apiLv2Info.put("gubun", "corpCode");
		apiLv2List.add(apiLv2Info);
		
		//2.정기보고서 주요정보
		//2.1 증자(감자) 현황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "1");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019004");
		apiLv2Info.put("apiName", "증자(감자) 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 증자(감자) 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/irdsSttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "irdsSttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "1");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019004");
		apiLv2Info.put("apiName", "증자(감자) 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 증자(감자) 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/irdsSttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "irdsSttus");
		apiLv2List.add(apiLv2Info);
		
		//2.2 배당에 관한 사항
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "2");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019005");
		apiLv2Info.put("apiName", "배당에 관한 사항");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 배당에 관한 사항을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/alotMatter.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "alotMatter");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "2");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019005");
		apiLv2Info.put("apiName", "배당에 관한 사항");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 배당에 관한 사항을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/alotMatter.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "alotMatter");
		apiLv2List.add(apiLv2Info);
		
		//2.3 자기주식 취득 및 처분 현황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "3");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019006");
		apiLv2Info.put("apiName", "자기주식 취득 및 처분 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 자기주식 취득 및 처분 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/tesstkAcqsDspsSttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "tesstkAcqsDspsSttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "3");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019006");
		apiLv2Info.put("apiName", "자기주식 취득 및 처분 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 자기주식 취득 및 처분 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/tesstkAcqsDspsSttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "tesstkAcqsDspsSttus");
		apiLv2List.add(apiLv2Info);
		
		//2.4 최대주주 현황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "4");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019007");
		apiLv2Info.put("apiName", "최대주주 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 최대주주 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/hyslrSttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "hyslrSttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "4");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019007");
		apiLv2Info.put("apiName", "최대주주 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 최대주주 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/hyslrSttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "hyslrSttus");
		apiLv2List.add(apiLv2Info);
		
		//2.5 최대주주 변동현황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "5");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019008");
		apiLv2Info.put("apiName", "최대주주 변동현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 최대주주 변동현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/hyslrChgSttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "hyslrChgSttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "5");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019008");
		apiLv2Info.put("apiName", "최대주주 변동현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 최대주주 변동현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/hyslrChgSttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "hyslrChgSttus");
		apiLv2List.add(apiLv2Info);
		
		//2.6 소액주주 현황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "6");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019009");
		apiLv2Info.put("apiName", "소액주주 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 소액주주 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/mrhlSttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "mrhlSttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "6");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019009");
		apiLv2Info.put("apiName", "소액주주 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 소액주주 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/mrhlSttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "mrhlSttus");
		apiLv2List.add(apiLv2Info);
		
		//2.7 임원 현황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "7");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019009");
		apiLv2Info.put("apiName", "임원 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 임원 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/exctvSttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "exctvSttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "7");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019009");
		apiLv2Info.put("apiName", "임원 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 임원 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/exctvSttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "exctvSttus");
		apiLv2List.add(apiLv2Info);	
		
		//2.8 직원 현황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "8");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019011");
		apiLv2Info.put("apiName", "직원 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 직원 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/empSttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "empSttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "8");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019011");
		apiLv2Info.put("apiName", "직원 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 직원 현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/empSttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "empSttus");
		apiLv2List.add(apiLv2Info);
		
		//2.9 이사·감사의 개인별 보수현황(5억원 이상)	
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "9");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019012");
		apiLv2Info.put("apiName", "이사·감사의 개인별 보수현황(5억원 이상)");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 이사·감사의 개인별 보수현황(5억원 이상)을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/hmvAuditIndvdlBySttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "hmvAuditIndvdlBySttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "9");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019012");
		apiLv2Info.put("apiName", "이사·감사의 개인별 보수현황(5억원 이상)");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 이사·감사의 개인별 보수현황(5억원 이상)을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/hmvAuditIndvdlBySttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "hmvAuditIndvdlBySttus");
		apiLv2List.add(apiLv2Info);
		
		//2.10 이사·감사 전체의 보수현황(보수지급금액 - 이사·감사 전체)
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "10");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019013");
		apiLv2Info.put("apiName", "이사·감사 전체의 보수현황(보수지급금액 - 이사·감사 전체)");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 이사·감사 전체의 보수현황(보수지급금액 - 이사·감사 전체)을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/hmvAuditAllSttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "hmvAuditAllSttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "10");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019013");
		apiLv2Info.put("apiName", "이사·감사 전체의 보수현황(보수지급금액 - 이사·감사 전체)");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 이사·감사 전체의 보수현황(보수지급금액 - 이사·감사 전체)을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/hmvAuditAllSttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "hmvAuditAllSttus");
		apiLv2List.add(apiLv2Info);	

		//2.11 개인별 보수지급 금액(5억이상 상위5인)
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "11");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019014");
		apiLv2Info.put("apiName", "개인별 보수지급 금액(5억이상 상위5인)");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 개인별 보수지급 금액(5억이상 상위5인)을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/indvdlByPay.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "indvdlByPay");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "11");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019014");
		apiLv2Info.put("apiName", "개인별 보수지급 금액(5억이상 상위5인)");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 개인별 보수지급 금액(5억이상 상위5인)을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/indvdlByPay.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "indvdlByPay");
		apiLv2List.add(apiLv2Info);
		
		//2.12 타법인 출자현황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "12");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019015");
		apiLv2Info.put("apiName", "타법인 출자현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 타법인 출자현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/otrCprInvstmntSttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "otrCprInvstmntSttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "12");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019014");
		apiLv2Info.put("apiName", "타법인 출자현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 타법인 출자현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/otrCprInvstmntSttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "otrCprInvstmntSttus");
		apiLv2List.add(apiLv2Info);	
		
		//2.13 주식의 총수 현황
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "13");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019015");
		apiLv2Info.put("apiName", "주식의 총수 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 주식의총수현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/stockTotqySttus.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "stockTotqySttus");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "2");
		apiLv2Info.put("apiNum", "13");
		apiLv2Info.put("apiGrpCd", "DS002");
		apiLv2Info.put("apiId", "2019014");
		apiLv2Info.put("apiName", "주식의 총수 현황");
		apiLv2Info.put("apiExplanation", "정기보고서(사업, 분기, 반기보고서) 내에 주식의총수현황을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/stockTotqySttus.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "stockTotqySttus");
		apiLv2List.add(apiLv2Info);				
		
		//3. 정기보고서 재무정보
		//3.1 단일회사 주요계정
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "1");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2019016");
		apiLv2Info.put("apiName", "단일회사 주요계정");
		apiLv2Info.put("apiExplanation", "상장법인(유가증권, 코스닥) 및 주요 비상장법인(사업보고서 제출대상 & IFRS 적용)이 제출한 정기보고서 내에 XBRL재무제표의 주요계정과목(재무상태표, 손익계산서)을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/fnlttSinglAcnt.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "fnlttSinglAcnt");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "1");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2019016");
		apiLv2Info.put("apiName", "단일회사 주요계정");
		apiLv2Info.put("apiExplanation", "상장법인(유가증권, 코스닥) 및 주요 비상장법인(사업보고서 제출대상 & IFRS 적용)이 제출한 정기보고서 내에 XBRL재무제표의 주요계정과목(재무상태표, 손익계산서)을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/fnlttSinglAcnt.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "fnlttSinglAcnt");
		apiLv2List.add(apiLv2Info);
		
		//3.2 다중회사 주요계정
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "2");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2019017");
		apiLv2Info.put("apiName", "다중회사 주요계정");
		apiLv2Info.put("apiExplanation", "상장법인(유가증권, 코스닥) 및 주요 비상장법인(사업보고서 제출대상 & IFRS 적용)이 제출한 정기보고서 내에 XBRL재무제표의 주요계정과목(재무상태표, 손익계산서)을 제공합니다. (대상법인 복수조회 복수조회 가능)");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/fnlttMultiAcnt.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "fnlttMultiAcnt");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "2");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2019017");
		apiLv2Info.put("apiName", "다중회사 주요계정");
		apiLv2Info.put("apiExplanation", "상장법인(유가증권, 코스닥) 및 주요 비상장법인(사업보고서 제출대상 & IFRS 적용)이 제출한 정기보고서 내에 XBRL재무제표의 주요계정과목(재무상태표, 손익계산서)을 제공합니다. (대상법인 복수조회 복수조회 가능)");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/fnlttMultiAcnt.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "fnlttMultiAcnt");
		apiLv2List.add(apiLv2Info);
		
		//3.3 재무제표 원본파일(XBRL)
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "3");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2019019");
		apiLv2Info.put("apiName", "재무제표 원본파일(XBRL)");
		apiLv2Info.put("apiExplanation", "상장법인(유가증권, 코스닥) 및 주요 비상장법인(사업보고서 제출대상 & IFRS 적용)이 제출한 정기보고서 내에 XBRL재무제표의 원본파일(XBRL)을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/fnlttXbrl.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "ZIP");
		apiLv2Info.put("gubun", "fnlttXbrl");
		apiLv2List.add(apiLv2Info);		
		
		//3.4 단일회사 전체 재무제표
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "4");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2019017");
		apiLv2Info.put("apiName", "단일회사 전체 재무제표");
		apiLv2Info.put("apiExplanation", "상장법인(유가증권, 코스닥) 및 주요 비상장법인(사업보고서 제출대상 & IFRS 적용)이 제출한 정기보고서 내에 XBRL재무제표의 모든계정과목을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/fnlttSinglAcntAll.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "fnlttSinglAcntAll");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "4");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2019017");
		apiLv2Info.put("apiName", "단일회사 전체 재무제표");
		apiLv2Info.put("apiExplanation", "상장법인(유가증권, 코스닥) 및 주요 비상장법인(사업보고서 제출대상 & IFRS 적용)이 제출한 정기보고서 내에 XBRL재무제표의 모든계정과목을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/fnlttSinglAcntAll.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "fnlttSinglAcntAll");
		apiLv2List.add(apiLv2Info);		
		
		//3.5 XBRL택사노미재무제표양식
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "5");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2020001");
		apiLv2Info.put("apiName", "XBRL택사노미재무제표양식");
		apiLv2Info.put("apiExplanation", "금융감독원 회계포탈에서 제공하는 IFRS 기반 XBRL 재무제표 공시용 표준계정과목체계(계정과목) 을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/xbrlTaxonomy.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "xbrlTaxonomy");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "5");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2020001");
		apiLv2Info.put("apiName", "XBRL택사노미재무제표양식");
		apiLv2Info.put("apiExplanation", "금융감독원 회계포탈에서 제공하는 IFRS 기반 XBRL 재무제표 공시용 표준계정과목체계(계정과목) 을 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/xbrlTaxonomy.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "xbrlTaxonomy");
		apiLv2List.add(apiLv2Info);	
		
		//3.6 단일회사 주요 재무지표
		apiLv2Info = new HashMap<String , Object>();
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "5");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2020001");
		apiLv2Info.put("apiName", "단일회사 주요 재무지표");
		apiLv2Info.put("apiExplanation", "상장법인(유가증권, 코스닥) 및 주요 비상장법인(사업보고서 제출대상 & IFRS 적용)이 제출한 정기보고서 내에 XBRL재무제표의 주요 재무지표를 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/xbrlTaxonomy.json");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "JSON");
		apiLv2Info.put("gubun", "xbrlTaxonomy");
		apiLv2List.add(apiLv2Info);
		apiLv2Info.put("apiLv", "3");
		apiLv2Info.put("apiNum", "5");
		apiLv2Info.put("apiGrpCd", "DS003");
		apiLv2Info.put("apiId", "2020001");
		apiLv2Info.put("apiName", "단일회사 주요 재무지표");
		apiLv2Info.put("apiExplanation", "상장법인(유가증권, 코스닥) 및 주요 비상장법인(사업보고서 제출대상 & IFRS 적용)이 제출한 정기보고서 내에 XBRL재무제표의 주요 재무지표를 제공합니다.");
		apiLv2Info.put("method", "GET");
		apiLv2Info.put("url", "https://opendart.fss.or.kr/api/xbrlTaxonomy.xml");
		apiLv2Info.put("encode", "UTF-8");
		apiLv2Info.put("outFormat", "XML");
		apiLv2Info.put("gubun", "xbrlTaxonomy");
		apiLv2List.add(apiLv2Info);			
		
	
		return resultMap;
	}
}
