/*주식 종목 내역*/
CREATE TABLE STOCKS_LIST
(
	STOCKS_CODE        VARCHAR2(6)  NOT NULL ,
	STOCKS_NAME      VARCHAR2(100)  NOT NULL ,
	STOCKS_GUBUN      VARCHAR2(50)  NOT NULL ,
	REG_DATE             DATE  DEFAULT SYSDATE,
CONSTRAINT  STOCKS_LIST_PK PRIMARY KEY(STOCKS_CODE)
);

COMMENT ON TABLE STOCKS_LIST IS '종목내역'; 
COMMENT ON COLUMN STOCKS_LIST.STOCKS_CODE IS '종목코드';
COMMENT ON COLUMN STOCKS_LIST.STOCKS_NAME IS '종목명';
COMMENT ON COLUMN STOCKS_LIST.STOCKS_GUBUN IS '종목구분';
COMMENT ON COLUMN STOCKS_LIST.REG_DATE IS '등록일';

/*DART API 정보*/
CREATE TABLE STOCKS_DART_API_LIST(
API_GRP_CD  VARCHAR2(10) NOT NULL ,
API_GRP_NUM  NUMBER(2,0) ,
API_GRP_NM  VARCHAR2(100) ,
API_NUM  NUMBER(2,0) ,
API_NM  VARCHAR2(100) ,
API_ID  VARCHAR2(10) NOT NULL ,
DETAIL  VARCHAR2(300) ,
URL_GUBUN  VARCHAR2(50) ,
MATHOD  VARCHAR2(5) ,
ENCODING  VARCHAR2(10) ,
JSON_YN  VARCHAR2(1) DEFAULT 'N' ,
XML_YN  VARCHAR2(1) DEFAULT 'N' ,
ZIP_YN  VARCHAR2(1) DEFAULT 'N' ,
REG_DATE  DATE DEFAULT SYSDATE ,
CONSTRAINT  STOCKS_DART_API_LIST_PK PRIMARY KEY(API_GRP_CD,API_ID)
);
COMMENT ON TABLE STOCKS_DART_API_LIST  IS 'DART API 정보';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.API_GRP_CD IS 'API그룹코드';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.API_GRP_NUM IS 'API그룹순번';
COMMENT ON COLUMN STOCKS_DART_API_LIST.API_GRP_NM IS 'API그룹명';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.API_NUM IS 'API순번';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.API_NM IS 'API명';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.API_ID IS 'API아이디';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.DETAIL IS '상세 설명';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.URL_GUBUN IS '요청URL';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.MATHOD IS '메서드';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.ENCODING IS '인코딩';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.JSON_YN IS '출력포멧 JSON 사용여부';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.XML_YN IS '출력포멧 XML 사용여부';	
COMMENT ON COLUMN STOCKS_DART_API_LIST.ZIP_YN IS '출력포멧 ZIP 사용여부';	

